author:
  name: ThePanaceya

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false

leap-day:
  social_links:
    - { platform: telegram, user_url: "https://t.me/meshtastic_mykolaiv" }